### PR TITLE
Lots of security fixes, mostly checking access to organizations

### PR DESCRIPTION
**Pull request by rvm-peercode**
Apply input validation to organization IDs submitted by the user: always check if the user has access to the requested organization ID or IDs, and throw an exception if he does not.

### CODE REVIEW

**Comment by mddejong** [comment]
Is it a good idea to approve this while the phpstan issue is open?

**Comment by rvm-peercode** [comment]
> Is it a good idea to approve this while the phpstan issue is open?

The phpstan issues come from the 2.x branch, not the changes in this one, but there's no hurry. I can rebase as soon as the 2.x branch is clean again.

**Comment by mddejong** [comment]
Apart from the previously discussed request id. 

I thought that in track maintenance we would not check on organization?

**Comment by rvm-peercode** [comment]
Well, following best practices, I've tried to find locations where a frontend filter was not accompanied by a backend validation, in order to add this validation to the backend. This is important to do from a security by design perspective. It also prevents possible issues when a class is copied in order to use it for different functionality.

My changes should not have any functional impact, since the frontend filters were already in place.

**Pull request merged**
